### ISSUE TITLE
Can access and use admin endpoints such as /user_balance or /user_kyc without logging in

### ISSUE THREAD

**Issue by 4855062503** [zap-me/beryllium#5]
Steps to reproduce:

Go into a private window or incognito in your browser of choice and try any admin endpoints such as:

`/user_balance`
`/user_kyc`

and test out if the functions work or not.

For me, I was able to download my own KYC information without being signed in, and check my balance.

**Comment by djpnewton** [comment]
good catch

try now

**Comment by eoliveros** [comment]
just tried again and this is no longer accessible when not login.
