### ISSUE TITLE
Getting AttributeError since commit 21...8f6

### ISSUE THREAD

**Issue by 4855062503** [zap-me/beryllium#57]
I believe Erick has mentioned the error [here](https://github.com/zap-me/ops/issues/168#issuecomment-1179815112)

I have been experiencing this `AttributeError` too.

I believe the error has spawned from [this](https://github.com/zap-me/beryllium/commit/21258809cd4e69cefc4b31beba72b7fea088b8f6) commit.

**Comment by djpnewton** [comment]
hopefully fixed https://github.com/zap-me/beryllium/pull/58

**Comment by djpnewton** [comment]
can you pull master and retest

**Comment by 4855062503** [comment]
@djpnewton 
Pulled from master, works.
Will close this issue now.

**Comment by djpnewton** [comment]
nice work @eoliveros
