### ISSUE TITLE
Submitting 'Trouble accessing your account' returns nothing.

### ISSUE THREAD

**Issue by 4855062503** [zap-me/beryllium#7]
This may not be that important:

Steps to reproduce:

Sign in to beryllium then when asked to present a 2FA email code, click the radio button 'Can not access mail account?' then press 'Submit'.

Nothing is returned to the user.

**Comment by eoliveros** [comment]
so the user has no way to access the email, so it looks like its supposed to send an email to admin@zap.me so we could do something about it afterwards. But im not sure whether that's how this thing is suppose to work.  Tested by sending an email from beryllium to admin@zap.me, looks like this is being filtered. its not going to spam/junk folder. 

@djpnewton - is admin@zap.me supposed to get an email when the radio button is selected?

**Comment by djpnewton** [comment]
Yes an email is sent to the admin.

@4855062503 maybe you could do a PR that alerts the user 'A message has been sent to the administrator'

**Comment by eoliveros** [comment]
found the email being filtered in one of my other folders. so it does go to the admin@zap.me address:
![image](https://user-images.githubusercontent.com/47799652/151907347-a87f1cd5-a00d-4e06-828c-d34fbee72b98.png)

The question i guess would be, how do we give the user access once we get this email.

**Comment by djpnewton** [comment]
Well it would have to be a manual process i guess
